version: "3.9"
services:

  bits:
    image: tradebits:latest
    restart: always
    ports:
      - ${LOGSTASH_INTERNAL_PASSWORD:-}:8080

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017/

  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - 6379:6397
    environment:
      - REDIS_PASSWORD=admin
