version: "3.2"
services:
  redis:
    image: redis:latest
    ports:
      - 7379:7379
  dgraph-standalone:
    image: dgraph/standalone:latest
    ports:
      - 7080:7080
      - 8080:8080
      - 9080:9080
      - 8000:8000
    command: dgraph zero & dgraph alpha