version: "3.9"
services:

  bits:
    build: .
    ports:
      - 8080:8080
    environment:
      MARKET_PORT: ${MARKET_PORT:-}
      MARKET_NAME: ${MARKET_NAME:-}
      MARKET_DESCR: ${MARKET_DESCR:-}
      MARKET_IMG: ${MARKET_IMG:-}
      MARKET_WORKTIME: ${MARKET_WORKTIME:-}
      MARKET_FEE: ${MARKET_FEE:-}
      MARKET_DELIMITER: ${MARKET_DELIMITER:-}
      MARKET_PRIVATEKEY: ${MARKET_PRIVATEKEY:-}
      MARKET_PUBLICKEY: ${MARKET_PUBLICKEY:-}

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_NAME:-}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_NAME:-}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD:-}
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017/

  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - 6379:6379
