version: "3.9"
services:

  bits:
    build: .
    ports:
      - 8080:8080
    environment:
      REDIS_HOST: localhost:6379
      MONGO_HOST: mongodb://localhost:27017
      GRAYLOG_HOST: udp://localhost:12201
      GRAYLOG_API: http://lcoalhost:9000/api/system/inputs
      MARKET_PORT: :8080
      MARKET_NAME: Example market name
      MARKET_DESCR: >
       Example of some market description kinda extended to ensure if fits well all checkboxes and fields on different devices on different applications. Duplication: Example of some market description kinda extended to ensure if fits well all checkboxes and fields on different devices on different applications. And agin: Example of some market description kinda extended to ensure if fits well all checkboxes and fields on different devices on different applications.
      MARKET_IMG: https://upload.wikimedia.org/wikipedia/commons/9/9a/BTC_Logo.svg
      MARKET_WORKTIME: 24/7
      MARKET_FEE: "86"
      MARKET_DELIMITER: "2"
      MARKET_PRIVATEKEY: >
        MIISKQIBAAKCBAEApAqr6+MbKqDAAiU+8XTu55krjllICL1tPS8TheV8xLiWetxCE2t+mYx9qyl7a2C9Cy5y4Eu/t/v9WHQ2p0T2U6Jt+wbgJQtsOoXuBXU8LKmOwMVxNJLgqCBiyn+YPWPDqEENSO8E+wawolKfvg+jfryvcTWztmMw609VCrghhpVz0ezPlmhS5mBK/AGSOMV/v4Zph/F30+TLLFa0LjhSZHH5WDmaDXybZlDr+lGOfjg3agG1fbOIAdkcuHIfI/24vF4jovgOnYLZGbOO0792gBVHqEps/b7gH5PMoZi7AJCFW66Y0NaXgM+oF1ifp6CNQZfscypSfVJMGYf66ZB4h6VFTQlXQGUJaHzCorMa9HKBszuMm6jNKqK62PinzSMVtZDvRB9/Fd6lxgBzdSO3entnYMshL3ez5zsQAesUkPgrbDyz9lxYt/5rOMEkgG2f/9HSVOsHV5scrOT08HXdpa9HfqeJWc5iK/Kny9+0cazRyXNM2JB83XbvrG4xPsvO/00mtQEnPCAMRkAIf93Fexd1V5ZH0hpXMCY2PoN6B0UkKerRX4cp3ldeWaJyBdfJHXi1uTLqFs35pnOiSfyDFrCeKlmRpCCHIicl/qxatdAsnbMl73p7bVyY7cQ6clCS4SfEsICNae2R/QtN8tp4gHO5ZaZmOSb+4qFA+IzCS5XSoDTgNqbPG/a8OO626bwkwqEMQtEC5mm+ckDtaqiD9iGXLFzTM4dEW0j8ba8MCn/FGR9i5Nfaf56kFDnxW26w+fVQti+zzEIowmMZq42Ifm6dNASXo2d1cLN/QiXLqZMEQ1xL6ATzHkXx4LjrRcCSJm8hKYipQ6ag/4XQEE2nCvnrzqzd//G69bR/MUzu7N7WCaNOmuTor7ve3YdaphCiQ2dZGq1lIEFMzSvtPfbxnjBVOGY/TEMh8t01W/CYLqbv8/OrXSC4v5ILyoXlR1IWuXGEdiH5Ihd0rxr8bONO1JMGCuAcxkTbZs9ONbnPzsJkdRCaUcrK4SYCP3wzvlKraS8yIbB5HEUKvF3XIbQ0y9qQa4qtBiVplieoLXRtBkDmk9Gqi/W5PwJwirBQWsra6bYog/EaG2uuy98z3myGLxn6rbkr1hCB3sCloFYKsXLWC+ezh7wjDHkn+obIOPRrseI9OSAxFKdYimyisAe68Tueg2UJLRArsT2/V6VcSoeeN198BQiBCB3dFKcp0BMdqi0GYoeR10g8hYvPd1qJ8gAq0VXC1O8PblVwSwNWGNTzvbw299anKHxbLURSPtViu0u0YHunwJZbs0UWE/OaZhp67Nhw/VN/FBp0w7xoK7RHW8qwC7hb62CZpwd8541agOf3TJVgKLFP8oXJ6ESPDwIDAQABAoIEAHZ4qo9S1pTjwagLBDlX7Q5gZb+JpWeCfvlYHW5vPbvJYAxdNG9YC/eTKlNKQzNai00e/6ITsuOKXv7Z93q4aHogbfOElK7MYB6oCS3x7EKJNmrsbYS9qvhhY1fB7M4xVeYXDSQmU1+EBl9E8s9N9hMa7E4DrcXEP1lCUzXJo5TSLPJoZ8fFklGFK8Jy1AqiQE+vIFoovxTOQRnFiJ102bRnR+A6wZKJ8qVjPfnrmtB3gzXRBCVDWq+TAJYI/Yp9vER2bKBPLCb/kBFqx3UP6uI3/CeDkNF1X+IOWRQ//JY8ycNcBkuVH5fM4SXzQGLMphfAQ+ksoKSXohQyS7kROKsmZjVr0JLWJYRLzjm4xnfSlu89y5/DumDXY8A9XNrfQtd9U//MC3lc8jZcrwXjhKg1pYSXT2E7vzb5RedMwu6r/JhQAtyi9wPy/7bebqE+Cvazr4bastPHV19af7eGOExnmWfUUXMFhYsd1ad86ZHLcTtfRRmGyFcdhZzvfCtRAC8Lpi/FJHPc5WB68GiAXxY16+4Uv8vycBN7FWPyilfjzGlliE7IjCliyeZMVrL3k+zv97ZIGh3cJjfbfVKXxojFh4UoaPGy+EVnJp6WFXEHZqGB95zLxYZHAL9/H4LdxCZOFVQvk3H0PKIW3vXMaIjEixnpohwWmLBOK2EWL2BsLLAUtXQIKbbGTSMo9LhfgfrbT2wz5EHEG4FBLU6w/kNrNfs328OQdbOAegtkO9hOUyxAEgzxaDZJmG3WgbjN65JVvbIo/ogPWegdtBEi9WPdYBYMXyMyEIjDnsAUsgWOkrjdLYpmKzG7wyLJD2nUiJTVDZ1g0MXMqup4Jf55wuKtNk+TGLfY9n4A12mJxNAKbPLFs1qkGC+RWMEINZfulADzcF5rWFp8RYcZQUCR6J08FDS/azuTIN5zyPtxaQALBWv0xZi94yaCX0KwUrP9ZC/4Cb58kZ7uhqp0niJrZCxFUU9j6CNyWUApRXRrxeJxrpFZQLOIifaS5Ebv0nQDqsZm1KE8EowluvmCMNrlidHbowYSkNFS5IFRPMCmSZmE8+AyyaQiQSpUAv0ANkfgTPNVkPtCd20KIxbT3jdsQRrHH2hqAZGfv4ho2ktW664j9FPNjvs7thGu/aGUnxDQDCu60TRyrzm1Ygote9XB8lw1eIYKLuzzyQyfjVn1COgbFMVjCLKWD42uI7ybnfhFhj/Zlyc/v+bEzRnj2CGdIaOwxxxhP0ONkoYUhcKMQOMHUNr6uoR5hhWsjiRgiQc8/5H6aPk8ru8G8T+D892/ZNP5VW5utAo84vat5Kx+wNn7PUDGIWWlGaUxeBOD7jf2c+dmY7Dg7bjLwcPJ/MRjWokCggIBAMcDyd/H59pHCIR7zQeZO/iH0KXEk+NeomOIfhSheC0jCb7rIgaaBiMKHMsikXTYcM/OPsZcSnH54sLRkQrTO1eiMx0sRV5/uT2a52uRGdhsd+LrinZzGdCmwk7oCd46rAcp8YKjHWVG0wPNCNzJKh3JKOdo1R/3bOUNJQ+a+Gf3HbdbpTDb4S78jJ3vT8VvDcLef4/z5OUoajptCok4QmZw3jyiXSCW2VFgIXWDHdiK+tHoOnOKpLouoG3d8FNWjDbdNPhBBqV9qdL5FUhSL4CqCYlBVQlNEhL//9lVl123BmPJUnpmGV2eOhSADOZWb9Jxxu+ATODVBlUKOILMFJQsCXIQjsS5hDy5F/N26ZFoHBD0Wkop9n8ZcfUxRLv7Y3iF+MRl4WLwtAOlOWcG19ynKGZ1HGKS1VRoy0JoBUafUpTDclQ7jICvxV+xUosKYdGNvxwKp4ETWrGuYQFm9PMjB69RpoIRBEyO6tSdK7DX/qBrmuAkIPwRdSlP0/VUcVUh1qSLxGwxuQBiSm2vWvdy1OFA11YNhWgcIZhwZ6RRFT6cccMENhnNZFpXQPojOHtEo/UhnkVww5yKu9znB5uZVrcOX6R7cNDEhCWW8fvICx6R+efxlKWECvSMEnAZ3OQW9Cytw5wp8kdcM4Dd+k6Y0N9uq8aHoBTPmdrGddKbAoICAQDTA0dgglEVxs7sYc4M691movJPvycJcWrIkUgZLWklrF/+r9P4Afj7AH7H3Kxpc3s6L4TOw5uRRfi5X8k7FbdYwd14zweV0FiN0wRtfd0ulL4PkMMY/y+GJj22yu1XdXyleGUOYlAy33cDp5wTYdTBXcS7qvS4q1zLhe1p7oRBy7k80rwrRyLwopUBAqK4lIKoy1C2TgpbLyB8diaT/va9avYv5LjV7072Ggz7GQYUzSbN47ZMC7SW6URyTFoxHbmr//e/cFnP5+zEOjxtfSy12GMyNGSn/EQQvLwEJGIFvwCX9DwGUknaI9jG5+kOJpgAg0URz/GTtRfFFUQStxIN3BnZ1W0rEWu20aRHwUdkT58JOijFc2bZMyLpXtBk3111H1oIc4WjJ7r8yM14lS46/FGZv2mM4K50IJa5y18ozpbPgxThyOeNHJF0BpQKhWYxBiqyaK46UuBXXghnYC/lMBqYCIXvqDXGnjb0I5AVjawxGu2nCSAMYle49RBZfijddt7xTsrnW2KcHNNVh8vGUrEQeJ4q6P4axSF9PZo8ZWzIGkGT0g8wtF6eWU1qPKXxH6ny+J/3aINQHRBZps2rtIXD0pRCKgtTPfPSkwYYS5vP6Hae2Ub0J4LE/3yX6jo4UXW2YLpgaLz5O4FQT6rxZNRyT1oBmNaLG1RBIxKSnQKCAgEAk9WpoVVTUp8PobKBRJK8rMre4DTdkrnasUtUNSkZJ5Zuh+cM2JCT3HWHnBIqsPyTGJrhoOIv3ui8XPHl53+wBlIT3CjlwuPoC+5E2G/qHg29JNDJg2HPHGKz1n+hzPYSkiPDJsLadEAfQiSN38yDP6sNepEyOFPJDYEtNaFtw3UbGvi2Bkxfw1KRdkSuIkBznX1AjwOi1eOmvY4AlJw5HvXa8Hm/6hSEjGF3mV5zzka3OTRkLy4fXbqDK/oAqzeQYrUBwyQytr5ZZ8Hl4FpEtTQab14buBQLSBfoy148Wb46vedwIEI1t4hxJodUjcpJuK8SExlggmdcE9HK1saYxtTLk3LfSx1wMNdiBlYf/Qa0SpfpdkwjspiJQZV+tJFye7YxbFsuCRw67LZQpMq9kUiOx0VZd5QRammKC+NPf/2cD6v8ArxVi8aGPKZxZZ2pukusWj1D3qss5O5fWvZLIU21SLPDl7ziT6ieop+6M9zPZgVo//V2lyi0uqJ1FjnLEm1Xj9XPbHunLLTXCxGG5mfj4QwUqfTTU9oJzr45DyO4P1FhZHd9ZL9hO4azWtzM+SytCswVUQoKFQAtu1PXH+vRMZw4yet0i3BfpbiyOtGICQZw+K5JOIaUyMJAdAuSPdEbQxE1TI0QT5gbHjBG3xm/lyoT6h8XeD4a0Rw5q98CggIAGvCNOU4J6hzSqC0ocE/gmUzuYK4H3tXDC045BTXd+bhTHSH3ju85iVob1Ypf3KqordoJO5iPkPF8+rW27DsuiD9f9h+AWWkbFSg+pXfvOBY3WadisRtLRvY05NRtjr/qJPoE9NwqXwRWnnnUnEjeL7238zm1OqpuE3HKyL5x1jCbOp+w9FmFpXEsUs+yVJxpPgGPEWdPPSr8G8e9zyE7AR3Zxm2OB4og65yR0bD1LMywSpLq4DSSXr3zRiBnV2PzI3lveNpwLPHwMXE568SSY7j3mR5FR4kWa4ic/G5ksVUcT0oYK7pvwVDYSTSsdWkJ+O7Jb6e7sN7q5Pd9FGKZBHn4Nu5fnKMBvHpxXdPYOH9Nz5DESckc9Vfo+iBnvKkjtmNFTFTrV9QntEQyr1VkbJVwGY/tetXoj9zlQV0sjfoqGN4kWVsb7NEb5NM+LUWwsUuXQeXJcJrKF31i10fZdYo5qvVTnDA+hVgHrg2oRIgs1qwYcT3iAJLBnlRzPOm1b+jQN8CWeQkawtGPTZkjs/M0teSgVNwgLOzEBMhLm7BbPgTUIHouBErS1aaTEqAhk3I2cVW6noySTzUWtEtucKCAf2qwEO5rObpsGZM5sPpeLyH/mvIkc+FjeaEgmAiIXE5SF/GrecmFbtBhBw7UxTLZSKrG0/NeWK4piJNguKUCggIBAKYKS3NtE0Uyg5rVgwRV8jXoukAMrsdjBtiPgNwxsNmWSrRrO8zUyeAzp3bOLuBEK2MqXUD6qLw2wFGaGlaSqNtfbemcXpyymYDvNMvYX9fd/fz1tRJ3Us2HsmouSfhws2z6NGu//jSVm2PHKaAy2at8+tqiwjf8eBPEH3ZRNW3Dpm9C8+yBccvVdUXcbVguAp2TIU4iMrhrBdW4GQ28qxlXkYjYgM16xSN3WzVGHkr0ETcvckzYAnvY2Gz/ZgfyvJ3Gee2be+2bIIrhP05eTbKMaMCrWFM2PvNLbrg3DiiJ2gP5gBJ+GrjlDGroA7FczMFI+ETn/A4lWbYLQQeXeggSZ3wWilLe70/3GPkJlsThgVd91l5qjiiwIjgVlUOJjzGPrdU/ElF6of+R0cwqvwcrCn7l6z0YEuXVBL5fJOMzJJ8F6+9S7GdxxuglVolsP2p6IVzKyVPbdQzVSA4It0tWRoaPysFfuBi/1wK2Ij2UJnCebHDAH1WqAM4uITRs1bADpUsTWJURp82y6c26wFOpfeYlZhJ1XhNE0VC2/4IsSt+KCmfhOST+IV3B6e3K2dNujmKwsOOEsM9GrtYbH7r0+CUObq2milDDtaaoAxjtVJ4rTdcm8/QZBLujckg+gJEEOG5LEd5K5S8WeUjJR2TsFkDako/7NKj7cZsAHvU9
    depends_on:
      - mongo
      - redis
      - graylog
    logging:
      driver: "gelf"
      options:
        gelf-address: udp://localhost:12201
        tag: "tradebits"

  mongo:
    image: mongo:4.2
    ports:
      - 27017:27017
    hostname: mongo
      - "host.docker.internal:host-gateway"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin

  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    extra_hosts:
      - "host.docker.internal:host-gateway"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Dlog4j2.formatMsgNoLookups=true -Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1g

  graylog:
    image: graylog/graylog:4.2
    environment:
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_HTTP_EXTERNAL_URI: http://127.0.0.1:9000/
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
    links:
      - mongo
      - elasticsearch
    restart: always
    depends_on:
      - mongo
      - elasticsearch
    ports:
      - 9000:9000
      - 1514:1514
      - 1514:1514/udp
      - 12201:12201
      - 12201:12201/udp