/*
 * TradeBits
 *
 * In this API description you can find description of ways markets communicate with each other and users.   Each sign of message user send to market is additionally reinforced by market name as indtent to ensure markets will not try to proceed same operations with users on other markets. That is not mention in API, but implemented on server and client sides.   Each procedure on specific market need to be reinforced by market name in senders message, to prevent mimic behavior by markets collecting data. That will guarantee, that only owner of the private key is able to process transactions on specific market.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"encoding/json"
	"log"
	"net/http"
	"os"

	"tradebits/mongo"
	"tradebits/redis"
	"tradebits/swagger"

	"github.com/joho/godotenv"
)

func readConfigField(field string) string {
	envar, found := os.LookupEnv(field)
	if !found {
		log.Fatal("problem loading .ENV field", found)
	}
	return envar
}

func initMongo() {
	mongoErr := mongo.OpenMongo(
		readConfigField("MONGO_HOST"),
		readConfigField("MONGO_NAME"),
		readConfigField("MONGO_PASSWORD"),
		readConfigField("MONGO_DB"),
	)
	if mongoErr != nil {
		log.Fatal(mongoErr)
	}
	mongo.CreateCollection("user")
	mongo.CreateCollection("market")
	mongo.CreateCollection("trades")
	mongo.CreateCollection("recover")
}

func initInfoResponse() {
	m := map[string]string{
		"name":      readConfigField("MARKET_NAME"),
		"mkey":      readConfigField("MARKET_PUBLICKEY"),
		"descr":     readConfigField("MARKET_DESCR"),
		"img":       readConfigField("MARKET_IMG"),
		"worktime":  readConfigField("MARKET_WORKTIME"),
		"fee":       readConfigField("MARKET_FEE"),
		"delimiter": readConfigField("MARKET_DELIMITER"),
	}
	respbytes, infoEjectErr := json.Marshal(m)
	if infoEjectErr != nil {
		log.Panic("failed to marshall info to bytes")
	}
	swagger.MarketInfoResponse = respbytes
}

func init() {
	if err := godotenv.Load(); err != nil {
		log.Panic("No .env file found")
	}
	redis.Setup(readConfigField("REDIS_HOST"))
	initMongo()
	initInfoResponse()
}

func main() {
	log.Printf("Server starting...")
	router := swagger.NewRouter()
	log.Fatal(http.ListenAndServe(readConfigField("MARKET_PORT"), router))
}
