go run "c:\Users\dangd\Documents\sync_tree_server\____tests\info.go"
go run "c:\Users\dangd\Documents\sync_tree_server\____tests\calc_tests\main.go"
go run "c:\Users\dangd\Documents\sync_tree_server\____tests\data_tests\main.go"
go run "c:\Users\dangd\Documents\sync_tree_server\____tests\lock_tests\main.go"
go run "c:\Users\dangd\Documents\sync_tree_server\____tests\user_tests\main.go"
go run "c:\Users\dangd\Documents\sync_tree_server\____tests\asset_tests\main.go"