type User {
    id: ID!
    pubkey: String! @id @search(by: [hash])
    balance: Int!
    messages: [String]
    orders: [Order] @hasInverse(field: "user")
    operations: [Operation] @hasInverse(field: "user")
}

type Order {
    id: ID!
    offer: Int!
    recieve: Int!
    ratio: Float!
    user: User @hasInverse(field: "orders")
    market: NetMember
}

type NetMember {
    id: ID!
    name: String! @id @search(by: [term])
    pubkey: String!
    link: String!
}

type Operation {
    id: ID!
    desciption: String!
    user: User @hasInverse(field: "operations")
}
