type User {
    id: ID!
    name: String! @id @search(by: [fulltext])
    adress: String! @id
    meskey: String! @id
    balances: [Balance]
    chats: [Chat]
    trades: [Trade] @hasInverse(field: "owner")
}

type Balance {
    market: String!
    balance: int!
}

type Chat {
    messages: [String]
}

type Market {
    
}

type Trade {
    offer: int!
    recieve: int!
    user: [User] @hasInverse(field: "trades")
    market: [Market] @hasInverse(field: "trades")
}

