type User {
    id: ID!
    name: String! @id @search(by: [fulltext])
    pubkey: String! @id @search(by: [hash])
    balances: [Balance]
    chats: [Chat]
    buys: [Trade] @hasInverse(field: "user")
    sells: [Trade] @hasInverse(field: "user")
}

type Balance {
    market: String!
    balance: int!
}

type Chat {
    messages: [String]
}

type Market {
    id: ID!
    name: String! @id @search(by: [fulltext])
    pubkey: String! @id @search(by: [hash])
    descr: String!
    img: String!
    inputfee: int!
    outputfee: int!
    worktime: String!
    buys: [Trade] @hasInverse(field: "market")
    sells: [Trade] @hasInverse(field: "market")
}

type Buy {
    offer: int!
    recieve: int!
    user: [User] @hasInverse(field: "buys")
    market: [Market] @hasInverse(field: "buys")
}

type Sell {
    offer: int!
    recieve: int!
    user: [User] @hasInverse(field: "sells")
    market: [Market] @hasInverse(field: "sells")
}
