type User {
    id: ID!
    name: String! @id @search(by: [fulltext])
    adress: String! @id
    meskey: String! @id
    balances: [Balance]
    chats: [Chat] @hasInverse(field: "members")
}

type Balance {
    market: String!
    balance: int!
}

type 