// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.1
// source: api/api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//Response (universal response, when no return value required)
type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{0}
}

type InfIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InfIn) Reset() {
	*x = InfIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfIn) ProtoMessage() {}

func (x *InfIn) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfIn.ProtoReflect.Descriptor instead.
func (*InfIn) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{1}
}

type InfOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InfOut) Reset() {
	*x = InfOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfOut) ProtoMessage() {}

func (x *InfOut) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfOut.ProtoReflect.Descriptor instead.
func (*InfOut) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{2}
}

type UserRequests struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserRequests) Reset() {
	*x = UserRequests{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserRequests) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequests) ProtoMessage() {}

func (x *UserRequests) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequests.ProtoReflect.Descriptor instead.
func (*UserRequests) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{3}
}

type MarketRequests struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MarketRequests) Reset() {
	*x = MarketRequests{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarketRequests) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketRequests) ProtoMessage() {}

func (x *MarketRequests) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketRequests.ProtoReflect.Descriptor instead.
func (*MarketRequests) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{4}
}

type InfIn_Adress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Adress []byte `protobuf:"bytes,1,opt,name=adress,proto3" json:"adress,omitempty"`
}

func (x *InfIn_Adress) Reset() {
	*x = InfIn_Adress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfIn_Adress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfIn_Adress) ProtoMessage() {}

func (x *InfIn_Adress) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfIn_Adress.ProtoReflect.Descriptor instead.
func (*InfIn_Adress) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{1, 0}
}

func (x *InfIn_Adress) GetAdress() []byte {
	if x != nil {
		return x.Adress
	}
	return nil
}

type InfIn_Text struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *InfIn_Text) Reset() {
	*x = InfIn_Text{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfIn_Text) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfIn_Text) ProtoMessage() {}

func (x *InfIn_Text) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfIn_Text.ProtoReflect.Descriptor instead.
func (*InfIn_Text) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{1, 1}
}

func (x *InfIn_Text) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type InfIn_UserMarketAdresses struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MarketAdress []byte `protobuf:"bytes,1,opt,name=market_adress,json=marketAdress,proto3" json:"market_adress,omitempty"`
	UserAdress   []byte `protobuf:"bytes,2,opt,name=user_adress,json=userAdress,proto3" json:"user_adress,omitempty"`
}

func (x *InfIn_UserMarketAdresses) Reset() {
	*x = InfIn_UserMarketAdresses{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfIn_UserMarketAdresses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfIn_UserMarketAdresses) ProtoMessage() {}

func (x *InfIn_UserMarketAdresses) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfIn_UserMarketAdresses.ProtoReflect.Descriptor instead.
func (*InfIn_UserMarketAdresses) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{1, 2}
}

func (x *InfIn_UserMarketAdresses) GetMarketAdress() []byte {
	if x != nil {
		return x.MarketAdress
	}
	return nil
}

func (x *InfIn_UserMarketAdresses) GetUserAdress() []byte {
	if x != nil {
		return x.UserAdress
	}
	return nil
}

type InfOut_User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicName     string   `protobuf:"bytes,1,opt,name=public_name,json=publicName,proto3" json:"public_name,omitempty"`
	Balance        uint64   `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	MessageKey     []byte   `protobuf:"bytes,3,opt,name=message_key,json=messageKey,proto3" json:"message_key,omitempty"`
	MarketAdresses [][]byte `protobuf:"bytes,4,rep,name=market_adresses,json=marketAdresses,proto3" json:"market_adresses,omitempty"`
	MarketBalances []uint64 `protobuf:"varint,5,rep,packed,name=market_balances,json=marketBalances,proto3" json:"market_balances,omitempty"`
}

func (x *InfOut_User) Reset() {
	*x = InfOut_User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfOut_User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfOut_User) ProtoMessage() {}

func (x *InfOut_User) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfOut_User.ProtoReflect.Descriptor instead.
func (*InfOut_User) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{2, 0}
}

func (x *InfOut_User) GetPublicName() string {
	if x != nil {
		return x.PublicName
	}
	return ""
}

func (x *InfOut_User) GetBalance() uint64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *InfOut_User) GetMessageKey() []byte {
	if x != nil {
		return x.MessageKey
	}
	return nil
}

func (x *InfOut_User) GetMarketAdresses() [][]byte {
	if x != nil {
		return x.MarketAdresses
	}
	return nil
}

func (x *InfOut_User) GetMarketBalances() []uint64 {
	if x != nil {
		return x.MarketBalances
	}
	return nil
}

type InfOut_MarketInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name           string          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MessageKey     []byte          `protobuf:"bytes,2,opt,name=messageKey,proto3" json:"messageKey,omitempty"`
	ImageLink      string          `protobuf:"bytes,3,opt,name=imageLink,proto3" json:"imageLink,omitempty"`
	Description    string          `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	OperationCount uint64          `protobuf:"varint,5,opt,name=operationCount,proto3" json:"operationCount,omitempty"`
	Buys           []*InfOut_Trade `protobuf:"bytes,6,rep,name=buys,proto3" json:"buys,omitempty"`
	Sells          []*InfOut_Trade `protobuf:"bytes,7,rep,name=sells,proto3" json:"sells,omitempty"`
	ActiveBuys     uint64          `protobuf:"varint,8,opt,name=activeBuys,proto3" json:"activeBuys,omitempty"`
	ActiveSells    uint64          `protobuf:"varint,9,opt,name=activeSells,proto3" json:"activeSells,omitempty"`
	InputFee       uint64          `protobuf:"varint,10,opt,name=inputFee,proto3" json:"inputFee,omitempty"`
	OutputFee      uint64          `protobuf:"varint,11,opt,name=outputFee,proto3" json:"outputFee,omitempty"`
	WorkTime       string          `protobuf:"bytes,12,opt,name=workTime,proto3" json:"workTime,omitempty"`
	Delimiter      uint64          `protobuf:"varint,14,opt,name=delimiter,proto3" json:"delimiter,omitempty"`
}

func (x *InfOut_MarketInfo) Reset() {
	*x = InfOut_MarketInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfOut_MarketInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfOut_MarketInfo) ProtoMessage() {}

func (x *InfOut_MarketInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfOut_MarketInfo.ProtoReflect.Descriptor instead.
func (*InfOut_MarketInfo) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{2, 1}
}

func (x *InfOut_MarketInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InfOut_MarketInfo) GetMessageKey() []byte {
	if x != nil {
		return x.MessageKey
	}
	return nil
}

func (x *InfOut_MarketInfo) GetImageLink() string {
	if x != nil {
		return x.ImageLink
	}
	return ""
}

func (x *InfOut_MarketInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *InfOut_MarketInfo) GetOperationCount() uint64 {
	if x != nil {
		return x.OperationCount
	}
	return 0
}

func (x *InfOut_MarketInfo) GetBuys() []*InfOut_Trade {
	if x != nil {
		return x.Buys
	}
	return nil
}

func (x *InfOut_MarketInfo) GetSells() []*InfOut_Trade {
	if x != nil {
		return x.Sells
	}
	return nil
}

func (x *InfOut_MarketInfo) GetActiveBuys() uint64 {
	if x != nil {
		return x.ActiveBuys
	}
	return 0
}

func (x *InfOut_MarketInfo) GetActiveSells() uint64 {
	if x != nil {
		return x.ActiveSells
	}
	return 0
}

func (x *InfOut_MarketInfo) GetInputFee() uint64 {
	if x != nil {
		return x.InputFee
	}
	return 0
}

func (x *InfOut_MarketInfo) GetOutputFee() uint64 {
	if x != nil {
		return x.OutputFee
	}
	return 0
}

func (x *InfOut_MarketInfo) GetWorkTime() string {
	if x != nil {
		return x.WorkTime
	}
	return ""
}

func (x *InfOut_MarketInfo) GetDelimiter() uint64 {
	if x != nil {
		return x.Delimiter
	}
	return 0
}

type InfOut_Adresses struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MarketAdresses [][]byte `protobuf:"bytes,1,rep,name=marketAdresses,proto3" json:"marketAdresses,omitempty"`
}

func (x *InfOut_Adresses) Reset() {
	*x = InfOut_Adresses{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfOut_Adresses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfOut_Adresses) ProtoMessage() {}

func (x *InfOut_Adresses) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfOut_Adresses.ProtoReflect.Descriptor instead.
func (*InfOut_Adresses) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{2, 2}
}

func (x *InfOut_Adresses) GetMarketAdresses() [][]byte {
	if x != nil {
		return x.MarketAdresses
	}
	return nil
}

type InfOut_Messages struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Messages [][]byte `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
}

func (x *InfOut_Messages) Reset() {
	*x = InfOut_Messages{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfOut_Messages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfOut_Messages) ProtoMessage() {}

func (x *InfOut_Messages) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfOut_Messages.ProtoReflect.Descriptor instead.
func (*InfOut_Messages) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{2, 3}
}

func (x *InfOut_Messages) GetMessages() [][]byte {
	if x != nil {
		return x.Messages
	}
	return nil
}

type InfOut_Bool struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value bool `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *InfOut_Bool) Reset() {
	*x = InfOut_Bool{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfOut_Bool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfOut_Bool) ProtoMessage() {}

func (x *InfOut_Bool) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfOut_Bool.ProtoReflect.Descriptor instead.
func (*InfOut_Bool) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{2, 4}
}

func (x *InfOut_Bool) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

type InfOut_Trade struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offer   uint64 `protobuf:"varint,1,opt,name=offer,proto3" json:"offer,omitempty"`
	Recieve uint64 `protobuf:"varint,2,opt,name=recieve,proto3" json:"recieve,omitempty"`
}

func (x *InfOut_Trade) Reset() {
	*x = InfOut_Trade{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfOut_Trade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfOut_Trade) ProtoMessage() {}

func (x *InfOut_Trade) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfOut_Trade.ProtoReflect.Descriptor instead.
func (*InfOut_Trade) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{2, 5}
}

func (x *InfOut_Trade) GetOffer() uint64 {
	if x != nil {
		return x.Offer
	}
	return 0
}

func (x *InfOut_Trade) GetRecieve() uint64 {
	if x != nil {
		return x.Recieve
	}
	return 0
}

type UserRequests_Create struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey   []byte `protobuf:"bytes,1,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	MesssageKey []byte `protobuf:"bytes,2,opt,name=MesssageKey,proto3" json:"MesssageKey,omitempty"`
	PublicName  string `protobuf:"bytes,3,opt,name=PublicName,proto3" json:"PublicName,omitempty"`
	Sign        []byte `protobuf:"bytes,4,opt,name=Sign,proto3" json:"Sign,omitempty"`
}

func (x *UserRequests_Create) Reset() {
	*x = UserRequests_Create{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserRequests_Create) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequests_Create) ProtoMessage() {}

func (x *UserRequests_Create) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequests_Create.ProtoReflect.Descriptor instead.
func (*UserRequests_Create) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{3, 0}
}

func (x *UserRequests_Create) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *UserRequests_Create) GetMesssageKey() []byte {
	if x != nil {
		return x.MesssageKey
	}
	return nil
}

func (x *UserRequests_Create) GetPublicName() string {
	if x != nil {
		return x.PublicName
	}
	return ""
}

func (x *UserRequests_Create) GetSign() []byte {
	if x != nil {
		return x.Sign
	}
	return nil
}

type UserRequests_Send struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey      []byte `protobuf:"bytes,1,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	SendAmount     uint64 `protobuf:"varint,2,opt,name=SendAmount,proto3" json:"SendAmount,omitempty"`
	RecieverAdress []byte `protobuf:"bytes,3,opt,name=RecieverAdress,proto3" json:"RecieverAdress,omitempty"`
	Sign           []byte `protobuf:"bytes,4,opt,name=Sign,proto3" json:"Sign,omitempty"`
}

func (x *UserRequests_Send) Reset() {
	*x = UserRequests_Send{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserRequests_Send) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequests_Send) ProtoMessage() {}

func (x *UserRequests_Send) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequests_Send.ProtoReflect.Descriptor instead.
func (*UserRequests_Send) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{3, 1}
}

func (x *UserRequests_Send) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *UserRequests_Send) GetSendAmount() uint64 {
	if x != nil {
		return x.SendAmount
	}
	return 0
}

func (x *UserRequests_Send) GetRecieverAdress() []byte {
	if x != nil {
		return x.RecieverAdress
	}
	return nil
}

func (x *UserRequests_Send) GetSign() []byte {
	if x != nil {
		return x.Sign
	}
	return nil
}

type UserRequests_Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey []byte `protobuf:"bytes,1,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	Adress    []byte `protobuf:"bytes,2,opt,name=Adress,proto3" json:"Adress,omitempty"`
	Message   []byte `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
	Sign      []byte `protobuf:"bytes,4,opt,name=Sign,proto3" json:"Sign,omitempty"`
}

func (x *UserRequests_Message) Reset() {
	*x = UserRequests_Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserRequests_Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequests_Message) ProtoMessage() {}

func (x *UserRequests_Message) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequests_Message.ProtoReflect.Descriptor instead.
func (*UserRequests_Message) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{3, 2}
}

func (x *UserRequests_Message) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *UserRequests_Message) GetAdress() []byte {
	if x != nil {
		return x.Adress
	}
	return nil
}

func (x *UserRequests_Message) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *UserRequests_Message) GetSign() []byte {
	if x != nil {
		return x.Sign
	}
	return nil
}

type UserRequests_Buy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey []byte `protobuf:"bytes,1,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	Adress    []byte `protobuf:"bytes,2,opt,name=Adress,proto3" json:"Adress,omitempty"`
	Recieve   uint64 `protobuf:"varint,3,opt,name=Recieve,proto3" json:"Recieve,omitempty"`
	Offer     uint64 `protobuf:"varint,4,opt,name=Offer,proto3" json:"Offer,omitempty"`
	Sign      []byte `protobuf:"bytes,5,opt,name=Sign,proto3" json:"Sign,omitempty"`
}

func (x *UserRequests_Buy) Reset() {
	*x = UserRequests_Buy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserRequests_Buy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequests_Buy) ProtoMessage() {}

func (x *UserRequests_Buy) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequests_Buy.ProtoReflect.Descriptor instead.
func (*UserRequests_Buy) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{3, 3}
}

func (x *UserRequests_Buy) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *UserRequests_Buy) GetAdress() []byte {
	if x != nil {
		return x.Adress
	}
	return nil
}

func (x *UserRequests_Buy) GetRecieve() uint64 {
	if x != nil {
		return x.Recieve
	}
	return 0
}

func (x *UserRequests_Buy) GetOffer() uint64 {
	if x != nil {
		return x.Offer
	}
	return 0
}

func (x *UserRequests_Buy) GetSign() []byte {
	if x != nil {
		return x.Sign
	}
	return nil
}

type UserRequests_Sell struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey []byte `protobuf:"bytes,1,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	Adress    []byte `protobuf:"bytes,2,opt,name=Adress,proto3" json:"Adress,omitempty"`
	Recieve   uint64 `protobuf:"varint,3,opt,name=Recieve,proto3" json:"Recieve,omitempty"`
	Offer     uint64 `protobuf:"varint,4,opt,name=Offer,proto3" json:"Offer,omitempty"`
	Sign      []byte `protobuf:"bytes,5,opt,name=Sign,proto3" json:"Sign,omitempty"`
}

func (x *UserRequests_Sell) Reset() {
	*x = UserRequests_Sell{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserRequests_Sell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequests_Sell) ProtoMessage() {}

func (x *UserRequests_Sell) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequests_Sell.ProtoReflect.Descriptor instead.
func (*UserRequests_Sell) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{3, 4}
}

func (x *UserRequests_Sell) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *UserRequests_Sell) GetAdress() []byte {
	if x != nil {
		return x.Adress
	}
	return nil
}

func (x *UserRequests_Sell) GetRecieve() uint64 {
	if x != nil {
		return x.Recieve
	}
	return 0
}

func (x *UserRequests_Sell) GetOffer() uint64 {
	if x != nil {
		return x.Offer
	}
	return 0
}

func (x *UserRequests_Sell) GetSign() []byte {
	if x != nil {
		return x.Sign
	}
	return nil
}

type UserRequests_CancelTrade struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey    []byte `protobuf:"bytes,1,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	MarketAdress []byte `protobuf:"bytes,2,opt,name=MarketAdress,proto3" json:"MarketAdress,omitempty"`
	Sign         []byte `protobuf:"bytes,3,opt,name=Sign,proto3" json:"Sign,omitempty"`
}

func (x *UserRequests_CancelTrade) Reset() {
	*x = UserRequests_CancelTrade{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserRequests_CancelTrade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequests_CancelTrade) ProtoMessage() {}

func (x *UserRequests_CancelTrade) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequests_CancelTrade.ProtoReflect.Descriptor instead.
func (*UserRequests_CancelTrade) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{3, 5}
}

func (x *UserRequests_CancelTrade) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *UserRequests_CancelTrade) GetMarketAdress() []byte {
	if x != nil {
		return x.MarketAdress
	}
	return nil
}

func (x *UserRequests_CancelTrade) GetSign() []byte {
	if x != nil {
		return x.Sign
	}
	return nil
}

type MarketRequests_Create struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey   []byte `protobuf:"bytes,1,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	MesssageKey []byte `protobuf:"bytes,2,opt,name=MesssageKey,proto3" json:"MesssageKey,omitempty"`
	Name        string `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Img         string `protobuf:"bytes,4,opt,name=Img,proto3" json:"Img,omitempty"`
	Descr       string `protobuf:"bytes,5,opt,name=Descr,proto3" json:"Descr,omitempty"`
	InputFee    uint64 `protobuf:"varint,6,opt,name=inputFee,proto3" json:"inputFee,omitempty"`
	OutputFee   uint64 `protobuf:"varint,7,opt,name=outputFee,proto3" json:"outputFee,omitempty"`
	WorkTime    string `protobuf:"bytes,8,opt,name=workTime,proto3" json:"workTime,omitempty"`
	Delimiter   uint64 `protobuf:"varint,9,opt,name=delimiter,proto3" json:"delimiter,omitempty"`
	Sign        []byte `protobuf:"bytes,10,opt,name=Sign,proto3" json:"Sign,omitempty"`
}

func (x *MarketRequests_Create) Reset() {
	*x = MarketRequests_Create{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarketRequests_Create) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketRequests_Create) ProtoMessage() {}

func (x *MarketRequests_Create) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketRequests_Create.ProtoReflect.Descriptor instead.
func (*MarketRequests_Create) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{4, 0}
}

func (x *MarketRequests_Create) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *MarketRequests_Create) GetMesssageKey() []byte {
	if x != nil {
		return x.MesssageKey
	}
	return nil
}

func (x *MarketRequests_Create) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MarketRequests_Create) GetImg() string {
	if x != nil {
		return x.Img
	}
	return ""
}

func (x *MarketRequests_Create) GetDescr() string {
	if x != nil {
		return x.Descr
	}
	return ""
}

func (x *MarketRequests_Create) GetInputFee() uint64 {
	if x != nil {
		return x.InputFee
	}
	return 0
}

func (x *MarketRequests_Create) GetOutputFee() uint64 {
	if x != nil {
		return x.OutputFee
	}
	return 0
}

func (x *MarketRequests_Create) GetWorkTime() string {
	if x != nil {
		return x.WorkTime
	}
	return ""
}

func (x *MarketRequests_Create) GetDelimiter() uint64 {
	if x != nil {
		return x.Delimiter
	}
	return 0
}

func (x *MarketRequests_Create) GetSign() []byte {
	if x != nil {
		return x.Sign
	}
	return nil
}

type MarketRequests_Update struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey []byte `protobuf:"bytes,1,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	Img       string `protobuf:"bytes,2,opt,name=Img,proto3" json:"Img,omitempty"`
	Descr     string `protobuf:"bytes,3,opt,name=Descr,proto3" json:"Descr,omitempty"`
	InputFee  uint64 `protobuf:"varint,4,opt,name=inputFee,proto3" json:"inputFee,omitempty"`
	OutputFee uint64 `protobuf:"varint,5,opt,name=outputFee,proto3" json:"outputFee,omitempty"`
	WorkTime  string `protobuf:"bytes,6,opt,name=workTime,proto3" json:"workTime,omitempty"`
	Sign      []byte `protobuf:"bytes,7,opt,name=Sign,proto3" json:"Sign,omitempty"`
}

func (x *MarketRequests_Update) Reset() {
	*x = MarketRequests_Update{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarketRequests_Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketRequests_Update) ProtoMessage() {}

func (x *MarketRequests_Update) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketRequests_Update.ProtoReflect.Descriptor instead.
func (*MarketRequests_Update) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{4, 1}
}

func (x *MarketRequests_Update) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *MarketRequests_Update) GetImg() string {
	if x != nil {
		return x.Img
	}
	return ""
}

func (x *MarketRequests_Update) GetDescr() string {
	if x != nil {
		return x.Descr
	}
	return ""
}

func (x *MarketRequests_Update) GetInputFee() uint64 {
	if x != nil {
		return x.InputFee
	}
	return 0
}

func (x *MarketRequests_Update) GetOutputFee() uint64 {
	if x != nil {
		return x.OutputFee
	}
	return 0
}

func (x *MarketRequests_Update) GetWorkTime() string {
	if x != nil {
		return x.WorkTime
	}
	return ""
}

func (x *MarketRequests_Update) GetSign() []byte {
	if x != nil {
		return x.Sign
	}
	return nil
}

type MarketRequests_Deposit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey  []byte `protobuf:"bytes,1,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	UserAdress []byte `protobuf:"bytes,2,opt,name=UserAdress,proto3" json:"UserAdress,omitempty"`
	Amount     uint64 `protobuf:"varint,3,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Sign       []byte `protobuf:"bytes,4,opt,name=Sign,proto3" json:"Sign,omitempty"`
}

func (x *MarketRequests_Deposit) Reset() {
	*x = MarketRequests_Deposit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarketRequests_Deposit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketRequests_Deposit) ProtoMessage() {}

func (x *MarketRequests_Deposit) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketRequests_Deposit.ProtoReflect.Descriptor instead.
func (*MarketRequests_Deposit) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{4, 2}
}

func (x *MarketRequests_Deposit) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *MarketRequests_Deposit) GetUserAdress() []byte {
	if x != nil {
		return x.UserAdress
	}
	return nil
}

func (x *MarketRequests_Deposit) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *MarketRequests_Deposit) GetSign() []byte {
	if x != nil {
		return x.Sign
	}
	return nil
}

type MarketRequests_Withdrawal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey  []byte `protobuf:"bytes,1,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	UserAdress []byte `protobuf:"bytes,2,opt,name=UserAdress,proto3" json:"UserAdress,omitempty"`
	Amount     uint64 `protobuf:"varint,3,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Sign       []byte `protobuf:"bytes,4,opt,name=Sign,proto3" json:"Sign,omitempty"`
}

func (x *MarketRequests_Withdrawal) Reset() {
	*x = MarketRequests_Withdrawal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarketRequests_Withdrawal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketRequests_Withdrawal) ProtoMessage() {}

func (x *MarketRequests_Withdrawal) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketRequests_Withdrawal.ProtoReflect.Descriptor instead.
func (*MarketRequests_Withdrawal) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{4, 3}
}

func (x *MarketRequests_Withdrawal) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *MarketRequests_Withdrawal) GetUserAdress() []byte {
	if x != nil {
		return x.UserAdress
	}
	return nil
}

func (x *MarketRequests_Withdrawal) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *MarketRequests_Withdrawal) GetSign() []byte {
	if x != nil {
		return x.Sign
	}
	return nil
}

type MarketRequests_Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey []byte `protobuf:"bytes,1,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	Adress    []byte `protobuf:"bytes,2,opt,name=Adress,proto3" json:"Adress,omitempty"`
	Message   []byte `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
	Sign      []byte `protobuf:"bytes,4,opt,name=Sign,proto3" json:"Sign,omitempty"`
}

func (x *MarketRequests_Reply) Reset() {
	*x = MarketRequests_Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarketRequests_Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketRequests_Reply) ProtoMessage() {}

func (x *MarketRequests_Reply) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketRequests_Reply.ProtoReflect.Descriptor instead.
func (*MarketRequests_Reply) Descriptor() ([]byte, []int) {
	return file_api_api_proto_rawDescGZIP(), []int{4, 4}
}

func (x *MarketRequests_Reply) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *MarketRequests_Reply) GetAdress() []byte {
	if x != nil {
		return x.Adress
	}
	return nil
}

func (x *MarketRequests_Reply) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *MarketRequests_Reply) GetSign() []byte {
	if x != nil {
		return x.Sign
	}
	return nil
}

var File_api_api_proto protoreflect.FileDescriptor

var file_api_api_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x61, 0x70, 0x69, 0x22, 0x0a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0xa1, 0x01, 0x0a, 0x05, 0x49, 0x6e, 0x66, 0x49, 0x6e, 0x1a, 0x20, 0x0a, 0x06, 0x41, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x61, 0x64, 0x72, 0x65, 0x73, 0x73, 0x1a, 0x1a, 0x0a, 0x04,
	0x54, 0x65, 0x78, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x1a, 0x5a, 0x0a, 0x12, 0x55, 0x73, 0x65, 0x72,
	0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x41, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x12, 0x23,
	0x0a, 0x0d, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x5f, 0x61, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x41, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x41, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x22, 0xa3, 0x06, 0x0a, 0x06, 0x49, 0x6e, 0x66, 0x4f, 0x75, 0x74, 0x1a,
	0xb4, 0x01, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x61, 0x6c,
	0x61, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x62, 0x61, 0x6c, 0x61,
	0x6e, 0x63, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x6b,
	0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x4b, 0x65, 0x79, 0x12, 0x27, 0x0a, 0x0f, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x5f, 0x61,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x0e, 0x6d,
	0x61, 0x72, 0x6b, 0x65, 0x74, 0x41, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x12, 0x27, 0x0a,
	0x0f, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x73,
	0x18, 0x05, 0x20, 0x03, 0x28, 0x04, 0x52, 0x0e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x42, 0x61,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x1a, 0xae, 0x03, 0x0a, 0x0a, 0x4d, 0x61, 0x72, 0x6b, 0x65,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x26, 0x0a, 0x0e, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x25, 0x0a, 0x04, 0x62, 0x75, 0x79, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x6e, 0x66, 0x4f, 0x75, 0x74, 0x2e, 0x54, 0x72, 0x61,
	0x64, 0x65, 0x52, 0x04, 0x62, 0x75, 0x79, 0x73, 0x12, 0x27, 0x0a, 0x05, 0x73, 0x65, 0x6c, 0x6c,
	0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x6e,
	0x66, 0x4f, 0x75, 0x74, 0x2e, 0x54, 0x72, 0x61, 0x64, 0x65, 0x52, 0x05, 0x73, 0x65, 0x6c, 0x6c,
	0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x42, 0x75, 0x79, 0x73, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x42, 0x75, 0x79,
	0x73, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x53, 0x65, 0x6c, 0x6c, 0x73,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x53, 0x65,
	0x6c, 0x6c, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x46, 0x65, 0x65, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x46, 0x65, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x46, 0x65, 0x65, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x09, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x46, 0x65, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x77, 0x6f, 0x72, 0x6b, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x77, 0x6f, 0x72, 0x6b, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x65, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x65, 0x72, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x64, 0x65,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x72, 0x1a, 0x32, 0x0a, 0x08, 0x41, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x0e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x41, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x0e, 0x6d, 0x61, 0x72,
	0x6b, 0x65, 0x74, 0x41, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x1a, 0x26, 0x0a, 0x08, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x1a, 0x1c, 0x0a, 0x04, 0x42, 0x6f, 0x6f, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x1a, 0x37, 0x0a, 0x05, 0x54, 0x72, 0x61, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x66,
	0x66, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x6f, 0x66, 0x66, 0x65, 0x72,
	0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x63, 0x69, 0x65, 0x76, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x07, 0x72, 0x65, 0x63, 0x69, 0x65, 0x76, 0x65, 0x22, 0xe7, 0x05, 0x0a, 0x0c, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x1a, 0x7c, 0x0a, 0x06, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x4b, 0x65, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4b,
	0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x67, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x53, 0x69, 0x67, 0x6e, 0x1a, 0x80, 0x01, 0x0a, 0x04, 0x53, 0x65,
	0x6e, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79,
	0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x65, 0x6e, 0x64, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x53, 0x65, 0x6e, 0x64, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x26, 0x0a, 0x0e, 0x52, 0x65, 0x63, 0x69, 0x65, 0x76, 0x65, 0x72, 0x41, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e, 0x52, 0x65, 0x63, 0x69, 0x65, 0x76,
	0x65, 0x72, 0x41, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x67, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x53, 0x69, 0x67, 0x6e, 0x1a, 0x6d, 0x0a, 0x07,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x41, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x67, 0x6e, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x53, 0x69, 0x67, 0x6e, 0x1a, 0x7f, 0x0a, 0x03, 0x42,
	0x75, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79,
	0x12, 0x16, 0x0a, 0x06, 0x41, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x06, 0x41, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x65, 0x63, 0x69,
	0x65, 0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x52, 0x65, 0x63, 0x69, 0x65,
	0x76, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x05, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x67, 0x6e,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x53, 0x69, 0x67, 0x6e, 0x1a, 0x80, 0x01, 0x0a,
	0x04, 0x53, 0x65, 0x6c, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x4b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x06, 0x41, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x52,
	0x65, 0x63, 0x69, 0x65, 0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x52, 0x65,
	0x63, 0x69, 0x65, 0x76, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x53,
	0x69, 0x67, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x53, 0x69, 0x67, 0x6e, 0x1a,
	0x63, 0x0a, 0x0b, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x54, 0x72, 0x61, 0x64, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x09, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x22, 0x0a, 0x0c,
	0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x41, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x0c, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x41, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x67, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x53, 0x69, 0x67, 0x6e, 0x22, 0xb4, 0x06, 0x0a, 0x0e, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x1a, 0x8c, 0x02, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79,
	0x12, 0x20, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4b, 0x65, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4b,
	0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x49, 0x6d, 0x67, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x49, 0x6d, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x44, 0x65, 0x73, 0x63,
	0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x44, 0x65, 0x73, 0x63, 0x72, 0x12, 0x1a,
	0x0a, 0x08, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x46, 0x65, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x08, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x46, 0x65, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x46, 0x65, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x6f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x46, 0x65, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x77, 0x6f, 0x72, 0x6b,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x77, 0x6f, 0x72, 0x6b,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x65, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x65,
	0x72, 0x18, 0x09, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x67, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x53, 0x69, 0x67, 0x6e, 0x1a, 0xb8, 0x01, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x49, 0x6d, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x49, 0x6d,
	0x67, 0x12, 0x14, 0x0a, 0x05, 0x44, 0x65, 0x73, 0x63, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x44, 0x65, 0x73, 0x63, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x70, 0x75, 0x74,
	0x46, 0x65, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x69, 0x6e, 0x70, 0x75, 0x74,
	0x46, 0x65, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x46, 0x65, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x46, 0x65,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x77, 0x6f, 0x72, 0x6b, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x77, 0x6f, 0x72, 0x6b, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x53, 0x69, 0x67, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x53, 0x69, 0x67,
	0x6e, 0x1a, 0x73, 0x0a, 0x07, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x09, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x55, 0x73,
	0x65, 0x72, 0x41, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a,
	0x55, 0x73, 0x65, 0x72, 0x41, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x41, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x67, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x53, 0x69, 0x67, 0x6e, 0x1a, 0x76, 0x0a, 0x0a, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72,
	0x61, 0x77, 0x61, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b,
	0x65, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x41, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x41, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69,
	0x67, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x53, 0x69, 0x67, 0x6e, 0x1a, 0x6b,
	0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x41, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x67, 0x6e, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x53, 0x69, 0x67, 0x6e, 0x32, 0xc8, 0x02, 0x0a, 0x04,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2b, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x11, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x49, 0x6e, 0x66, 0x49, 0x6e, 0x2e, 0x41, 0x64, 0x72, 0x65, 0x73, 0x73, 0x1a,
	0x10, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x6e, 0x66, 0x4f, 0x75, 0x74, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x12, 0x3c, 0x0a, 0x09, 0x48, 0x61, 0x73, 0x54, 0x72, 0x61, 0x64, 0x65, 0x73, 0x12, 0x1d,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x6e, 0x66, 0x49, 0x6e, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4d,
	0x61, 0x72, 0x6b, 0x65, 0x74, 0x41, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x1a, 0x10, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x49, 0x6e, 0x66, 0x4f, 0x75, 0x74, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x12,
	0x33, 0x0a, 0x06, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x12, 0x11, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x49, 0x6e, 0x66, 0x49, 0x6e, 0x2e, 0x41, 0x64, 0x72, 0x65, 0x73, 0x73, 0x1a, 0x16, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x49, 0x6e, 0x66, 0x4f, 0x75, 0x74, 0x2e, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2f, 0x0a, 0x06, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x0f,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x6e, 0x66, 0x49, 0x6e, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x1a,
	0x14, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x6e, 0x66, 0x4f, 0x75, 0x74, 0x2e, 0x41, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x65, 0x73, 0x12, 0x3f, 0x0a, 0x08, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x12, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x6e, 0x66, 0x49, 0x6e, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x41, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73,
	0x1a, 0x14, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x6e, 0x66, 0x4f, 0x75, 0x74, 0x2e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x2e, 0x0a, 0x09, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x6e, 0x66, 0x49, 0x6e, 0x2e,
	0x54, 0x65, 0x78, 0x74, 0x1a, 0x10, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x6e, 0x66, 0x4f, 0x75,
	0x74, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x32, 0xb6, 0x02, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12,
	0x31, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x1a, 0x0d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2d, 0x0a, 0x04, 0x53, 0x65, 0x6e, 0x64, 0x12, 0x16, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x2e, 0x53, 0x65,
	0x6e, 0x64, 0x1a, 0x0d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x33, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x19, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x2e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x0d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x03, 0x42, 0x75, 0x79, 0x12, 0x15, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73,
	0x2e, 0x42, 0x75, 0x79, 0x1a, 0x0d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x04, 0x53, 0x65, 0x6c, 0x6c, 0x12, 0x16, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x2e, 0x53,
	0x65, 0x6c, 0x6c, 0x1a, 0x0d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0b, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x54, 0x72, 0x61, 0x64,
	0x65, 0x12, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x73, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x54, 0x72, 0x61, 0x64, 0x65,
	0x1a, 0x0d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32,
	0x98, 0x02, 0x0a, 0x06, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x12, 0x32, 0x0a, 0x05, 0x53, 0x70,
	0x61, 0x77, 0x6e, 0x12, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x1a,
	0x0d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33,
	0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d,
	0x61, 0x72, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x1a, 0x0d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x07, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x12, 0x1b,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x73, 0x2e, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x1a, 0x0d, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0a, 0x57, 0x69,
	0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x61, 0x6c, 0x12, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d,
	0x61, 0x72, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x2e, 0x57, 0x69,
	0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x61, 0x6c, 0x1a, 0x0d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x73, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x1a, 0x0d, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f,
	0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_api_proto_rawDescOnce sync.Once
	file_api_api_proto_rawDescData = file_api_api_proto_rawDesc
)

func file_api_api_proto_rawDescGZIP() []byte {
	file_api_api_proto_rawDescOnce.Do(func() {
		file_api_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_api_proto_rawDescData)
	})
	return file_api_api_proto_rawDescData
}

var file_api_api_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_api_api_proto_goTypes = []interface{}{
	(*Response)(nil),                  // 0: api.Response
	(*InfIn)(nil),                     // 1: api.InfIn
	(*InfOut)(nil),                    // 2: api.InfOut
	(*UserRequests)(nil),              // 3: api.UserRequests
	(*MarketRequests)(nil),            // 4: api.MarketRequests
	(*InfIn_Adress)(nil),              // 5: api.InfIn.Adress
	(*InfIn_Text)(nil),                // 6: api.InfIn.Text
	(*InfIn_UserMarketAdresses)(nil),  // 7: api.InfIn.UserMarketAdresses
	(*InfOut_User)(nil),               // 8: api.InfOut.User
	(*InfOut_MarketInfo)(nil),         // 9: api.InfOut.MarketInfo
	(*InfOut_Adresses)(nil),           // 10: api.InfOut.Adresses
	(*InfOut_Messages)(nil),           // 11: api.InfOut.Messages
	(*InfOut_Bool)(nil),               // 12: api.InfOut.Bool
	(*InfOut_Trade)(nil),              // 13: api.InfOut.Trade
	(*UserRequests_Create)(nil),       // 14: api.UserRequests.Create
	(*UserRequests_Send)(nil),         // 15: api.UserRequests.Send
	(*UserRequests_Message)(nil),      // 16: api.UserRequests.Message
	(*UserRequests_Buy)(nil),          // 17: api.UserRequests.Buy
	(*UserRequests_Sell)(nil),         // 18: api.UserRequests.Sell
	(*UserRequests_CancelTrade)(nil),  // 19: api.UserRequests.CancelTrade
	(*MarketRequests_Create)(nil),     // 20: api.MarketRequests.Create
	(*MarketRequests_Update)(nil),     // 21: api.MarketRequests.Update
	(*MarketRequests_Deposit)(nil),    // 22: api.MarketRequests.Deposit
	(*MarketRequests_Withdrawal)(nil), // 23: api.MarketRequests.Withdrawal
	(*MarketRequests_Reply)(nil),      // 24: api.MarketRequests.Reply
}
var file_api_api_proto_depIdxs = []int32{
	13, // 0: api.InfOut.MarketInfo.buys:type_name -> api.InfOut.Trade
	13, // 1: api.InfOut.MarketInfo.sells:type_name -> api.InfOut.Trade
	5,  // 2: api.Info.User:input_type -> api.InfIn.Adress
	7,  // 3: api.Info.HasTrades:input_type -> api.InfIn.UserMarketAdresses
	5,  // 4: api.Info.Market:input_type -> api.InfIn.Adress
	6,  // 5: api.Info.Search:input_type -> api.InfIn.Text
	7,  // 6: api.Info.Messages:input_type -> api.InfIn.UserMarketAdresses
	6,  // 7: api.Info.CheckName:input_type -> api.InfIn.Text
	14, // 8: api.User.Create:input_type -> api.UserRequests.Create
	15, // 9: api.User.Send:input_type -> api.UserRequests.Send
	16, // 10: api.User.Message:input_type -> api.UserRequests.Message
	17, // 11: api.User.Buy:input_type -> api.UserRequests.Buy
	18, // 12: api.User.Sell:input_type -> api.UserRequests.Sell
	19, // 13: api.User.CancelTrade:input_type -> api.UserRequests.CancelTrade
	20, // 14: api.Market.Spawn:input_type -> api.MarketRequests.Create
	21, // 15: api.Market.Update:input_type -> api.MarketRequests.Update
	22, // 16: api.Market.Deposit:input_type -> api.MarketRequests.Deposit
	23, // 17: api.Market.Withdrawal:input_type -> api.MarketRequests.Withdrawal
	24, // 18: api.Market.Reply:input_type -> api.MarketRequests.Reply
	8,  // 19: api.Info.User:output_type -> api.InfOut.User
	12, // 20: api.Info.HasTrades:output_type -> api.InfOut.Bool
	9,  // 21: api.Info.Market:output_type -> api.InfOut.MarketInfo
	10, // 22: api.Info.Search:output_type -> api.InfOut.Adresses
	11, // 23: api.Info.Messages:output_type -> api.InfOut.Messages
	12, // 24: api.Info.CheckName:output_type -> api.InfOut.Bool
	0,  // 25: api.User.Create:output_type -> api.Response
	0,  // 26: api.User.Send:output_type -> api.Response
	0,  // 27: api.User.Message:output_type -> api.Response
	0,  // 28: api.User.Buy:output_type -> api.Response
	0,  // 29: api.User.Sell:output_type -> api.Response
	0,  // 30: api.User.CancelTrade:output_type -> api.Response
	0,  // 31: api.Market.Spawn:output_type -> api.Response
	0,  // 32: api.Market.Update:output_type -> api.Response
	0,  // 33: api.Market.Deposit:output_type -> api.Response
	0,  // 34: api.Market.Withdrawal:output_type -> api.Response
	0,  // 35: api.Market.Reply:output_type -> api.Response
	19, // [19:36] is the sub-list for method output_type
	2,  // [2:19] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_api_proto_init() }
func file_api_api_proto_init() {
	if File_api_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserRequests); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarketRequests); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfIn_Adress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfIn_Text); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfIn_UserMarketAdresses); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfOut_User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_api_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfOut_MarketInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_api_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfOut_Adresses); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_api_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfOut_Messages); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_api_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfOut_Bool); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_api_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfOut_Trade); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_api_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserRequests_Create); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_api_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserRequests_Send); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_api_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserRequests_Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_api_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserRequests_Buy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_api_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserRequests_Sell); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_api_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserRequests_CancelTrade); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_api_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarketRequests_Create); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_api_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarketRequests_Update); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_api_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarketRequests_Deposit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_api_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarketRequests_Withdrawal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_api_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarketRequests_Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_api_api_proto_goTypes,
		DependencyIndexes: file_api_api_proto_depIdxs,
		MessageInfos:      file_api_api_proto_msgTypes,
	}.Build()
	File_api_api_proto = out.File
	file_api_api_proto_rawDesc = nil
	file_api_api_proto_goTypes = nil
	file_api_api_proto_depIdxs = nil
}
