swagger: "2.0"
info:
  version: "1.0.2"
  title: "TradeBits"
  description: >
   In this API description you can find description of ways markets communicate with each other and users.
   
   Each sign of message user send to market is additionally reinforced by market name as indtent to ensure markets will not try to proceed same operations with users on other markets. That is not mention in API, but implemented on server and client sides.
   
   Each procedure on specific market need to be reinforced by market name in senders message, to prevent mimic behavior by markets collecting data. That will guarantee, that only owner of the private key is able to process transactions on specific market. 
   
   ## API notions:

   - **ukey** - public key of the user, which is used by user to send messages and process operations on a related market 

   - **mkey** - public key of the market, which can be used to encrypt and verify messages
   
   - **hkey** - key of host added for additional security, for message verification. This is the public key of the node accepting the request
paths:
  /info/market:
    get:
      tags:
        - "info"
      summary: "get information about market"
      responses:
        "200":
          description: "OK"
          schema:
            type: string
            properties:
              name:
                type: string
              mkey:
                type: string
              descr:
                type: string
              img:
                type: string
              worktime:
                type: string
              fee:
                type: integer
              delimiter:
                type: integer
            example:
              name: "Best Market"
              mkey: "base64content"
              descr: "Best ever made"
              img: "http://image.link/img123"
              worktime: "9:00 - 23:00"
              fee: 86
              delimiter: 2
  /info/net:
    get:
      tags:
        - "info"
      summary: "get information about cuurent network members"
      responses:
        "200":
          description: "OK"
          schema:
            type: string
            properties:
              items:
                type: object
                properties:
                  name:
                    type: string
                  mkey:
                    type: string
                  link:
                    type: string
            example:
              - name: "Market name"
                mkey: "mktadress"
                link: "http://someadr.ru/helo"
              - name: "Market name"
                mkey: "mktadress"
                link: "http://someadr.ru/helo"
  /user/create:
    put:
      tags:
        - "user"
      summary: "creates new user in market"
      consumes:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            type: string
            properties:
              hkey:
                type: string
              ukey:
                type: string
              sign:
                type: string
            example:
              hkey: "putbase64contents"
              ukey: "putbase64contents"
              sign: "putbase64contents"
      responses:
        "201":
          description: "Created"
        "401":
          description: "Unauthorized (Sign verification error)"
        "403":
          description: "Forbidden (User exists)"
        "406":
          description: "Not accepable (Bad input)"
        "421":
          description: "Misdirected Request (Wrong host key - hkey)"
  /user/balance:
    get:
      tags:
        - "user"
      summary: "get user balance"
      consumes:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            type: string
            properties:
              ukey:
                type: string
            example:
              ukey: "putbase64contents"
      responses:
        "200":
          description: "OK"
          schema:
            type: string
            properties:
              balance:
                type: integer
            example:
              balance: 3872
        "404":
          description: "User not found"
        "405":
          description: "Invalid input"
  /user/messages:
    get:
      tags:
        - "user"
      summary: "get messages related to user"
      consumes:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            type: string
            properties:
              ukey:
                type: string
              offset:
                type: integer
            example:
              ukey: "putbase64contents"
              offset: 87
      responses:
        "200":
          description: "OK"
          schema:
            type: string
            properties:
              items:
                type: object
                properties:
                  name:
                    type: string
                  key:
                    type: string
                  link:
                    type: string
            example:
              - name: "Market name"
                key: "mktadress"
                link: "http://someadr.ru/helo"
              - name: "Market name"
                key: "mktadress"
                link: "http://someadr.ru/helo"
  /user/trades:
    get:
      tags:
        - "user"
      summary: "get user active trades"
      consumes:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            type: string
            properties:
              ukey:
                type: string
            example:
              ukey: "putbase64contents"
      responses:
        "200":
          description: "OK"
          schema:
            type: string
            properties:
              items:
                type: object
                properties:
                  offer:
                    type: integer
                  recieve:
                    type: integer
                  mkey:
                    type: string
            example:
              - offer: 12
                recieve: 25
                mkey: "mktadress"
              - offer: 42
                recieve: 15
                mkey: "anothermktadress"
        "404":
          description: "User not found"
        "405":
          description: "Invalid input"
  /user/message:
    put:
      tags:
        - "user"
      summary: "sends message from user to exchange"
      consumes:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            type: string
            properties:
              hkey:
                type: string
              ukey:
                type: string
              message:
                type: string
              sign:
                type: string
            example:
              hkey: "putbase64contents"
              ukey: "putbase64contents"
              message: "encrypted_message"
              sign: "putbase64contents"
      responses:
        "200":
          description: "OK"
        "401":
          description: "Sign verification error"
        "404":
          description: "User not found"
        "405":
          description: "Invalid input"
        "423":
          description: "Locked"
  /user/order:
    post:
      tags:
        - "user"
      summary: "make buy order for currency in different exchange"
      consumes:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            type: string
            properties:
              hkey:
                type: string
              ukey:
                type: string
              marketkey:
                type: string
              offer:
                type: integer
              recieve:
                type: integer
              sign:
                type: string
            example:
              hkey: "putbase64contents"
              ukey: "putbase64contents"
              marketkey: "putbase64contents"
              offer: 46582
              recieve: 3652
              sign: "putbase64contents"
      responses:
        "200":
          description: "OK"
        "401":
          description: "Sign verification error"
        "404":
          description: "User not found"
        "405":
          description: "Invalid input"
        "423":
          description: "Locked"
        "456":
          description: "Bad balance"
  /user/cancelorders:
    post:
      tags:
        - "user"
      summary: "cancel orders from user"
      consumes:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            type: string
            properties:
              hkey:
                type: string
              ukey:
                type: string
              sign:
                type: string
            example:
              hkey: "putbase64contents"
              ukey: "putbase64contents"
              sign: "putbase64contents"
      responses:
        "200":
          description: "OK"
        "401":
          description: "Sign verification error"
        "404":
          description: "User not found"
        "423":
          description: "Locked"
        "457":
          description: "No active trades"
  /market/create:
    put:
      tags:
        - "market"
      summary: "add market to network members"
      consumes:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            type: string
            properties:
              hkey:
                type: string
              mkey:
                type: string
              marketname:
                type: string
              marketlink:
                type: string
              sign:
                type: string
            example:
              hhey: "putbase64contents"
              mkey: "putbase64contents"
              marketname: "putbase64contents"
              marketlink: "http://link.example"
              sign: "signbase64"
      responses:
        "200":
          description: "OK"
        "401":
          description: "Sign verification error"
        "405":
          description: "Invalid input"
  /market/decrease:
    post:
      tags:
        - "market"
      summary: "decreases order from specific user"
      consumes:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            type: string
            properties:
              hkey:
                type: string
              mkey:
                type: string
              ukey:
                type: string
              newoffer:
                type: integer
              newrecieve:
                type: integer
              sign:
                type: string
            example:
              hkey: "putbase64contents"
              mkey: "putbase64contents"
              ukey: "putbase64contents"
              newoffer: 56
              newrecieve: 98
              sign: "signbase64"
      responses:
        "200":
          description: "OK"
        "401":
          description: "Sign verification error"
        "404":
          description: "Trade not found"
        "405":
          description: "Invalid input"
        "423":
          description: "Locked"
        "457":
          description: "No active trades"
  /market/related:
    get:
      tags:
        - "market"
      summary: "get best related trade from market"
      consumes:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            type: string
            properties:
              mkey:
                type: string
            example:
              mkey: "putbase64contents"
      responses:
        "200":
          description: "OK"
          schema:
            type: string
            properties:
              mkey:
                type: string
              offer:
                type: integer
              recieve:
                type: integer
            example:
              mkey: "base64adress"
              offer: 54
              recieve: 87
        "404":
          description: "Market not found"
        "405":
          description: "Invalid input"
  /market/close:
    delete:
      tags:
        - "market"
      summary: "closes order from specific user"
      consumes:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            type: string
            properties:
              hkey:
                type: string
              mkey:
                type: string
              ukey:
                type: string
              sign:
                type: string
            example:
              hkey: "putbase64contents"
              mkey: "putbase64contents"
              ukey: "putbase64contents"
              sign: "signbase64"
      responses:
        "200":
          description: "OK"
        "401":
          description: "Sign verification error"
        "404":
          description: "Trade not found"
        "405":
          description: "Invalid input"
        "423":
          description: "Locked"
        "457":
          description: "No active trades"
  #  ###################
  #   OPERATOR REQUESTS
  #  ###################
  /operator/message:
    put:
      tags:
        - "operator"
      summary: "sends message to user"
      consumes:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            type: string
            properties:
              hkey:
                type: string
              ukey:
                type: string
              message:
                type: string
              sign:
                type: string
            example:
              hkey: "putbase64contents"
              ukey: "putbase64contents"
              message: "putbase64contents"
              sign: "signbase64"
      responses:
        "200":
          description: "OK"
        "401":
          description: "Sign verification error"
        "404":
          description: "User not found"
        "405":
          description: "Invalid input"
  /operator/deposit:
    post:
      tags:
        - "operator"
      summary: "increase user balance by some amount"
      consumes:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            type: string
            properties:
              hkey:
                type: string
              ukey:
                type: string
              increase:
                type: integer
              sign:
                type: string
            example:
              hkey: "putbase64contents"
              ukey: "putbase64contents"
              increase: 673
              sign: "signbase64"
      responses:
        "200":
          description: "OK"
        "401":
          description: "Sign verification error"
        "404":
          description: "User not found"
        "405":
          description: "Invalid input"
        "423":
          description: "Locked"
  /operator/withdrawal:
    post:
      tags:
        - "operator"
      summary: "decrease user balance by some amount"
      consumes:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            type: string
            properties:
              hkey:
                type: string
              ukey:
                type: string
              decrease:
                type: integer
              sign:
                type: string
            example:
              hkey: "putbase64contents"
              ukey: "putbase64contents"
              decrease: 12345
              sign: "signbase64"
      responses:
        "200":
          description: "OK"
        "401":
          description: "Sign verification error"
        "404":
          description: "User not found"
        "405":
          description: "Invalid input"
        "423":
          description: "Locked"
        "456":
          description: "Bad balance"